name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title length
        run: |
          if [ "${{ github.event.pull_request.title }}" == "" ]; then
            echo "Pull Request title cannot be empty!"
            exit 1
          fi
